### ISSUE TITLE
Perrita

### ISSUE THREAD

**Issue by CeDimotta27** [pdepjm/2024-tp0-presentacion-bcochon#1]
El pueblo merece saber el nombre de tu bonita perrita >:((

**Comment by SofiaBaudo** [comment]
completamente de acuerdo!

**Comment by esoxonurb** [comment]
La gorda es _Eevee_, como el pokemon. A mi yo de 12 años le encargaron bautizarla y entre todas las propuestas de pokemones mi familia aceptó Eevee

**Comment by bcochon** [comment]
La gorda es _Eevee_, como el pokemon. A mi yo de 12 años le encargaron bautizarla y ante varias propuestas de nombres de pokemones mi familia aceptó Eevee 🐶
