### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by Valentin-Sosa** [pdepjm/2024-tp0-presentacion-bcochon#3]
Hola amigo millo, vi que mencionas que te gusta ir a conciertos ¿Que bandas te gusta ir a  ver? 
PD: Que casaca la del 2018. Vamos por la libertadoress 2024

**Comment by bcochon** [comment]
Genio qué tal. Soy más de festivales que otras cosas (capaz de estar parado 9hs con tal de quedarme en valla). Si viene alguna banda que me guste siempre intento estar. Estuve por ejemplo en el Quilmes Rock 2022 por Gorillaz y el año pasado en el Primavera Sound por Blur. También intento enganchar shows gratis cuando puedo, como el futurock que hacen (o hacían) en tecnopolis, que pude ver a Él mató y a Bandalos Chinos (entre más).
Y vamos River que este año la final es en casa !
